insert into diagnosis_questions (question_text, question_key, sort_order)
values
('いま一番やりたいことは？', 'goal', 1),
('いま困っていることは？', 'pain', 2),
('あなたのタイプは？', 'type', 3),
('作りたい成果物は？', 'output', 4),
('AIに任せたい範囲は？', 'range', 5),
('コードは触れる？', 'code', 6),
('資料は多い？', 'docs', 7),
('重視するものは？', 'priority', 8),
('月にどれくらい使いたい？', 'budget', 9),
('最終的に目指したい状態は？', 'future', 10)
on conflict (project_key, question_key) do nothing;

insert into diagnosis_answers (question_id, answer_text, answer_key, score_json, sort_order)
select q.id, v.answer_text, v.answer_key, v.score_json::jsonb, v.sort_order
from diagnosis_questions q
join (
  values
  ('goal','文章を書きたい','goal_0','{"types":{"writing":3},"tools":{"ChatGPT":3,"Claude":3}}',1),
  ('goal','サイトを作りたい','goal_1','{"types":{"site_builder":3},"tools":{"Claude Code":3,"Codex":3,"ChatGPT":2}}',2),
  ('goal','資料を整理したい','goal_2','{"types":{"research":3},"tools":{"NotebookLM":3,"Gemini":3,"ChatGPT":1}}',3),
  ('goal','調査したい','goal_3','{"types":{"research":3},"tools":{"Perplexity":3,"Felo":2,"Genspark":2}}',4),
  ('goal','音楽や動画を作りたい','goal_4','{"types":{"creative":3},"tools":{"Suno":3,"Udio":3,"Runway":3,"ChatGPT":2}}',5),
  ('goal','SNS投稿を伸ばしたい','goal_5','{"types":{"writing":2,"producer":1},"tools":{"ChatGPT":3,"Claude":2}}',6),
  ('goal','業務を自動化したい','goal_6','{"types":{"workflow":3},"tools":{"ChatGPT":2,"Codex":2,"Gemini":2}}',7),
  ('goal','AIを仕事に導入したい','goal_7','{"types":{"team":2,"producer":3},"tools":{"ChatGPT":3,"NotebookLM":2,"Gamma":2}}',8),
  ('pain','何から始めたらいいかわからない','pain_0','{"types":{"producer":2},"tools":{"ChatGPT":3}}',1),
  ('pain','AIが多すぎて選べない','pain_1','{"types":{"producer":3},"tools":{"ChatGPT":2}}',2),
  ('pain','プロンプトがうまく書けない','pain_2','{"types":{"writing":2},"tools":{"ChatGPT":2,"Claude":2}}',3),
  ('pain','実装で止まる','pain_3','{"types":{"developer":3},"tools":{"Codex":4,"Claude Code":2}}',4),
  ('pain','資料が多すぎる','pain_4','{"types":{"research":3},"tools":{"NotebookLM":4,"Gemini":2}}',5),
  ('pain','アイデアはあるが形にできない','pain_5','{"types":{"creative":2,"site_builder":2},"tools":{"ChatGPT":2,"Codex":2}}',6),
  ('pain','費用や利用制限が心配','pain_6','{"types":{"workflow":1},"tools":{"ChatGPT":1,"Perplexity":1}}',7),
  ('pain','チームで共有できない','pain_7','{"types":{"team":3},"tools":{"Gamma":2,"NotebookLM":2}}',8),
  ('type','考えるのが好き','type_0','{"types":{"producer":1},"tools":{"ChatGPT":1}}',1),
  ('type','書くのが好き','type_1','{"types":{"writing":2},"tools":{"ChatGPT":2,"Claude":2}}',2),
  ('type','作るのが好き','type_2','{"types":{"site_builder":2,"developer":1},"tools":{"Codex":2,"Claude Code":2}}',3),
  ('type','調べるのが好き','type_3','{"types":{"research":2},"tools":{"Perplexity":2,"NotebookLM":2}}',4),
  ('type','広げるのが好き','type_4','{"types":{"creative":1,"producer":1},"tools":{"ChatGPT":1}}',5),
  ('type','人を巻き込むのが好き','type_5','{"types":{"team":2},"tools":{"Gamma":2}}',6),
  ('output','X投稿','output_0','{"types":{"writing":2},"tools":{"ChatGPT":2}}',1),
  ('output','note記事','output_1','{"types":{"writing":2},"tools":{"Claude":2,"ChatGPT":2}}',2),
  ('output','LP','output_2','{"types":{"site_builder":3,"writing":1},"tools":{"ChatGPT":2,"Codex":2}}',3),
  ('output','ホームページ','output_3','{"types":{"site_builder":3},"tools":{"Codex":3,"Claude Code":2}}',4),
  ('output','アプリ','output_4','{"types":{"developer":3},"tools":{"Codex":4,"Claude Code":2}}',5),
  ('output','診断サイト','output_5','{"types":{"site_builder":2,"producer":2},"tools":{"ChatGPT":2,"Codex":3}}',6),
  ('output','スライド','output_6','{"types":{"team":1,"writing":1},"tools":{"Gamma":3,"Napkin AI":1}}',7),
  ('output','講演資料','output_7','{"types":{"writing":2,"team":1},"tools":{"Claude":2,"Gamma":2}}',8),
  ('output','音楽','output_8','{"types":{"creative":3},"tools":{"Suno":3,"Udio":3}}',9),
  ('output','マニュアル','output_9','{"types":{"workflow":2,"team":1},"tools":{"ChatGPT":2,"NotebookLM":2}}',10),
  ('output','データベース','output_10','{"types":{"developer":2,"workflow":2},"tools":{"Codex":2}}',11),
  ('range','壁打ちだけ','range_0','{"types":{"writing":1},"tools":{"ChatGPT":2}}',1),
  ('range','下書きまで','range_1','{"types":{"writing":2},"tools":{"ChatGPT":2,"Claude":2}}',2),
  ('range','設計まで','range_2','{"types":{"producer":2},"tools":{"Claude":2,"ChatGPT":2}}',3),
  ('range','実装まで','range_3','{"types":{"developer":2},"tools":{"Codex":3}}',4),
  ('range','改善まで','range_4','{"types":{"developer":2,"workflow":1},"tools":{"Codex":2,"ChatGPT":1}}',5),
  ('range','運用まで','range_5','{"types":{"workflow":3,"team":1},"tools":{"ChatGPT":2}}',6),
  ('code','まったく触れない','code_0','{"types":{"writing":1},"tools":{"ChatGPT":2}}',1),
  ('code','少しならわかる','code_1','{"types":{"site_builder":1},"tools":{"ChatGPT":1,"Codex":1}}',2),
  ('code','Claude Code / Codexを使い始めた','code_2','{"types":{"developer":3},"tools":{"Claude Code":3,"Codex":3}}',3),
  ('code','GitHubも使える','code_3','{"types":{"developer":3},"tools":{"Codex":3}}',4),
  ('code','エンジニアに近い','code_4','{"types":{"developer":4},"tools":{"Codex":4,"Claude Code":2}}',5),
  ('docs','ほとんどない','docs_0','{"types":{"producer":1},"tools":{"ChatGPT":1}}',1),
  ('docs','メモ程度','docs_1','{"types":{"writing":1},"tools":{"ChatGPT":1}}',2),
  ('docs','NotionやGoogle Driveに多い','docs_2','{"types":{"research":2},"tools":{"NotebookLM":3,"Gemini":2}}',3),
  ('docs','PDFや議事録が多い','docs_3','{"types":{"research":3},"tools":{"NotebookLM":4}}',4),
  ('docs','過去投稿や活動記録が大量にある','docs_4','{"types":{"research":2,"producer":1},"tools":{"NotebookLM":3,"Claude":1}}',5),
  ('priority','速さ','priority_0','{"types":{"workflow":1},"tools":{"ChatGPT":2}}',1),
  ('priority','正確さ','priority_1','{"types":{"research":2},"tools":{"Perplexity":2,"NotebookLM":2}}',2),
  ('priority','安さ','priority_2','{"types":{"workflow":1},"tools":{"ChatGPT":1}}',3),
  ('priority','表現力','priority_3','{"types":{"creative":2,"writing":1},"tools":{"Claude":2,"ChatGPT":1}}',4),
  ('priority','実装力','priority_4','{"types":{"developer":3},"tools":{"Codex":4}}',5),
  ('priority','調査力','priority_5','{"types":{"research":3},"tools":{"Perplexity":3,"Felo":2}}',6),
  ('priority','自動化','priority_6','{"types":{"workflow":3},"tools":{"Codex":2,"ChatGPT":2}}',7),
  ('priority','チーム共有','priority_7','{"types":{"team":3},"tools":{"Gamma":2,"NotebookLM":2}}',8),
  ('budget','無料中心','budget_0','{"types":{"workflow":1},"tools":{"ChatGPT":1}}',1),
  ('budget','月3,000円以内','budget_1','{"types":{"writing":1},"tools":{"ChatGPT":1}}',2),
  ('budget','月5,000円〜1万円','budget_2','{"types":{"producer":1},"tools":{"ChatGPT":1,"Claude":1}}',3),
  ('budget','月2万円以上','budget_3','{"types":{"developer":1,"producer":1},"tools":{"Codex":1,"Claude Code":1}}',4),
  ('budget','仕事なら投資したい','budget_4','{"types":{"producer":2,"team":1},"tools":{"ChatGPT":1,"Codex":1}}',5),
  ('future','AIを便利に使いたい','future_0','{"types":{"producer":1},"tools":{"ChatGPT":2}}',1),
  ('future','SNS発信を強くしたい','future_1','{"types":{"writing":3},"tools":{"ChatGPT":3,"Claude":2}}',2),
  ('future','サイトを作りたい','future_2','{"types":{"site_builder":3},"tools":{"Codex":3,"Claude Code":2}}',3),
  ('future','商品やサービスを作りたい','future_3','{"types":{"producer":3,"site_builder":1},"tools":{"ChatGPT":2,"Claude":2,"Codex":2}}',4),
  ('future','AIで仕事を仕組み化したい','future_4','{"types":{"workflow":3},"tools":{"ChatGPT":2,"Codex":2}}',5),
  ('future','AIを使って仲間とプロジェクトを動かしたい','future_5','{"types":{"team":3,"producer":2},"tools":{"ChatGPT":2,"Gamma":2}}',6)
) as v(question_key, answer_text, answer_key, score_json, sort_order)
on q.project_key = 'ai-fit-diagnosis' and q.question_key = v.question_key
on conflict do nothing;
